# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ameya/ddp/Modify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ameya/ddp/Modify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ameya/ddp/Modify/CMakeFiles /home/ameya/ddp/Modify/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ameya/ddp/Modify/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AABB_demo

# Build rule for target.
AABB_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AABB_demo
.PHONY : AABB_demo

# fast build rule for target.
AABB_demo/fast:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/build
.PHONY : AABB_demo/fast

AABB_demo.o: AABB_demo.cpp.o
.PHONY : AABB_demo.o

# target to build an object file
AABB_demo.cpp.o:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/AABB_demo.cpp.o
.PHONY : AABB_demo.cpp.o

AABB_demo.i: AABB_demo.cpp.i
.PHONY : AABB_demo.i

# target to preprocess a source file
AABB_demo.cpp.i:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/AABB_demo.cpp.i
.PHONY : AABB_demo.cpp.i

AABB_demo.s: AABB_demo.cpp.s
.PHONY : AABB_demo.s

# target to generate assembly for a file
AABB_demo.cpp.s:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/AABB_demo.cpp.s
.PHONY : AABB_demo.cpp.s

qrc_AABB_demo.o: qrc_AABB_demo.cxx.o
.PHONY : qrc_AABB_demo.o

# target to build an object file
qrc_AABB_demo.cxx.o:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/qrc_AABB_demo.cxx.o
.PHONY : qrc_AABB_demo.cxx.o

qrc_AABB_demo.i: qrc_AABB_demo.cxx.i
.PHONY : qrc_AABB_demo.i

# target to preprocess a source file
qrc_AABB_demo.cxx.i:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/qrc_AABB_demo.cxx.i
.PHONY : qrc_AABB_demo.cxx.i

qrc_AABB_demo.s: qrc_AABB_demo.cxx.s
.PHONY : qrc_AABB_demo.s

# target to generate assembly for a file
qrc_AABB_demo.cxx.s:
	$(MAKE) -f CMakeFiles/AABB_demo.dir/build.make CMakeFiles/AABB_demo.dir/qrc_AABB_demo.cxx.s
.PHONY : qrc_AABB_demo.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... AABB_demo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AABB_demo.o"
	@echo "... AABB_demo.i"
	@echo "... AABB_demo.s"
	@echo "... qrc_AABB_demo.o"
	@echo "... qrc_AABB_demo.i"
	@echo "... qrc_AABB_demo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

